cose.label = int / text
cose.values = any

Receipt_For_Consistency = #6.18(Signed_Consistency_Proof)

Signed_Consistency_Proof = [
  protected   : bstr .cbor RFC9162_SHA256_Consistency_Protected_Header,
  unprotected : RFC9162_SHA256_Consistency_Unprotected_Header,
  payload     : bstr / nil, ; Newer Merkle tree root
  signature   : bstr
]

RFC9162_SHA256_Consistency_Protected_Header = {
  &(alg: 1) ^ => int
  &(vds: 395) ^ => int
  * cose.label => cose.values
}

RFC9162_SHA256_Consistency_Unprotected_Header = {
  &(vdp: 396) ^ => RFC9162_SHA256_Verifiable_Consistency_Proofs
  * cose.label => cose.values
}

RFC9162_SHA256_Verifiable_Consistency_Proofs = {
  &(consistency-proof: -2) => RFC9162_SHA256_Consistency_Proofs
}

RFC9162_SHA256_Consistency_Proofs = [ + RFC9162_SHA256_Consistency_Proof ]

RFC9162_SHA256_Consistency_Proof = bstr .cbor [
   tree_size_1: uint,
   tree_size_2: uint,
   consistency_path: [ + bstr ]
]