name: "Update Editor's Copy"

on:
  push:
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore
  pull_request:
    paths-ignore:
    - README.md
    - CONTRIBUTING.md
    - LICENSE.md
    - .gitignore

jobs:
  build:
    name: "Update Editor's Copy"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Setup Ruby"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"

    - name: "Install Dependencies"
      shell: bash
      run: |
        set -eo pipefail
        gem install kramdown-rfc cddlc cddl edn-abnf
        pip install xml2rfc

    - name: "Validate CDDL and CBOR Examples from Draft XML"
      shell: bash
      run: |
        set -eo pipefail

        make draft-ietf-cose-merkle-tree-proofs.xml
        ./examples/validate-cbor-examples.sh draft-ietf-cose-merkle-tree-proofs.xml

    - name: "Validate CDDL and CBOR Examples from AUTH48 XML"
      shell: bash
      run: |
        set -eo pipefail
        ./examples/validate-cbor-examples.sh auth48/rfc9942.xml \
          --usage-diag an-example-cose-signature-w.cbor-diag \
          --inclusion-diag receipt-of-inclusion-2.cbor-diag \
          --consistency-diag example-consistency-receipt.cbor-diag

    - name: "Setup"
      id: setup
      run: date -u "+date=%FT%T" >>"$GITHUB_OUTPUT"

    - name: "Caching"
      uses: actions/cache@v4
      with:
        path: |
          .refcache
          .venv
          .gems
          node_modules
          .targets.mk
        key: i-d-${{ steps.setup.outputs.date }}
        restore-keys: i-d-

    - name: "Build Drafts"
      uses: martinthomson/i-d-template@v1
      with:
        token: ${{ github.token }}

    - name: "Update GitHub Pages"
      uses: martinthomson/i-d-template@v1
      if: ${{ github.event_name == 'push' }}
      with:
        make: gh-pages
        token: ${{ github.token }}

    - name: "Archive Built Drafts"
      uses: actions/upload-artifact@v4
      with:
        path: |
          draft-*.html
          draft-*.txt
